endpoint: "https://api-testnet.bybit.com"
trade_type: "usdt_perpetual"
regex: '(^\w+).*(BUY|SELL)\s*$'
logfile: "tradebot.log"

symbols:
  BTCUSDT:
    multiplier: 0.1
    buy_leverage: 1
    sell_leverage: 1
    close_policy: 1
    open_policy: 1
    take_profit: 5
    stop_loss: 5

  ETHUSDT:
    multiplier: 1.0
    buy_leverage: 1.5
    sell_leverage: 1.5
    target_profit: 0.2
